# Tool Catalog (SSOT)
# Canonical registry of tools available in CA360ยบ Portal ecosystem
# Version: 1.0
# Last Updated: 2025-12-19

tools:
  # CAD Tools
  - tool_id: catia-v5-vdi
    tool_class: CAD
    display_name: "CATIA V5 (VDI)"
    description: "CAD modeling and design for mechanical components"
    delivery_channel: VDI
    licensing:
      required: true
      model: concurrent
      server_type: flexlm
      pool_id: catia_v5_design
      checkout_mode: interactive
      constraints:
        max_duration_hours: 8
        requires_checkout_confirmation: true
    access:
      sso_required: true
      entitlement_groups:
        - eng_cad_users
        - phm_design_team
      export_control: ITAR
    workspace:
      mounts_required:
        - repo_node
        - project_exports
        - cad_templates
        - shared_datasets
    preflight_checks:
      - check_sso_valid
      - check_entitlement_group
      - check_license_available
      - check_vdi_session_capacity

  - tool_id: catia-v6-vdi
    tool_class: CAD
    display_name: "CATIA V6 (VDI)"
    description: "Advanced 3D CAD modeling and PLM integration"
    delivery_channel: VDI
    licensing:
      required: true
      model: concurrent
      server_type: flexlm
      pool_id: catia_v6_design
      checkout_mode: interactive
      constraints:
        max_duration_hours: 8
        requires_checkout_confirmation: true
    access:
      sso_required: true
      entitlement_groups:
        - eng_cad_users
        - phm_design_team
      export_control: ITAR
    workspace:
      mounts_required:
        - repo_node
        - project_exports
        - cad_templates
        - shared_datasets
    preflight_checks:
      - check_sso_valid
      - check_entitlement_group
      - check_license_available
      - check_vdi_session_capacity

  # CAE/Solver Tools
  - tool_id: ansys-hpc-solver
    tool_class: CAE
    display_name: "ANSYS Structural Solver (HPC)"
    description: "Finite element analysis and structural simulation"
    delivery_channel: HPC_JOB
    licensing:
      required: true
      model: token
      server_type: flexlm
      pool_id: ansys_hpc_structural
      checkout_mode: batch
      constraints:
        max_tokens_per_job: 128
        max_job_duration_hours: 48
    access:
      sso_required: true
      entitlement_groups:
        - eng_cae_users
        - phm_analysis_team
      export_control: ITAR
    workspace:
      mounts_required:
        - repo_node
        - project_exports
        - solver_inputs
        - solver_outputs
        - shared_datasets
    preflight_checks:
      - check_sso_valid
      - check_entitlement_group
      - check_license_tokens_available
      - check_hpc_queue_capacity
      - check_storage_quota

  - tool_id: nastran-hpc-solver
    tool_class: CAE
    display_name: "MSC Nastran Solver (HPC)"
    description: "Multidisciplinary structural analysis"
    delivery_channel: HPC_JOB
    licensing:
      required: true
      model: token
      server_type: flexlm
      pool_id: nastran_hpc_structural
      checkout_mode: batch
      constraints:
        max_tokens_per_job: 64
        max_job_duration_hours: 72
    access:
      sso_required: true
      entitlement_groups:
        - eng_cae_users
        - phm_analysis_team
      export_control: ITAR
    workspace:
      mounts_required:
        - repo_node
        - project_exports
        - solver_inputs
        - solver_outputs
        - shared_datasets
    preflight_checks:
      - check_sso_valid
      - check_entitlement_group
      - check_license_tokens_available
      - check_hpc_queue_capacity
      - check_storage_quota

  # Analysis Tools
  - tool_id: matlab-vdi-analysis
    tool_class: ANALYSIS
    display_name: "MATLAB (VDI)"
    description: "Numerical computing and data analysis"
    delivery_channel: VDI
    licensing:
      required: true
      model: concurrent
      server_type: flexlm
      pool_id: matlab_engineering
      checkout_mode: interactive
      constraints:
        max_duration_hours: 8
        toolbox_addons:
          - optimization_toolbox
          - signal_processing_toolbox
          - control_systems_toolbox
    access:
      sso_required: true
      entitlement_groups:
        - eng_analysis_users
        - phm_analysis_team
      export_control: EAR
    workspace:
      mounts_required:
        - repo_node
        - project_exports
        - analysis_scripts
        - shared_datasets
    preflight_checks:
      - check_sso_valid
      - check_entitlement_group
      - check_license_available
      - check_vdi_session_capacity

  - tool_id: python-jupyter-container
    tool_class: ANALYSIS
    display_name: "Python Jupyter Notebooks (Container)"
    description: "Interactive data analysis and visualization with Python"
    delivery_channel: CONTAINER
    licensing:
      required: false
      model: open_source
    access:
      sso_required: true
      entitlement_groups:
        - eng_analysis_users
        - phm_analysis_team
        - data_science_team
      export_control: EAR
    workspace:
      mounts_required:
        - repo_node
        - project_exports
        - notebooks
        - shared_datasets
    preflight_checks:
      - check_sso_valid
      - check_entitlement_group
      - check_container_capacity
      - check_storage_quota

  - tool_id: python-jupyter-vdi
    tool_class: ANALYSIS
    display_name: "Python Jupyter Notebooks (VDI)"
    description: "Interactive data analysis and visualization with Python on VDI"
    delivery_channel: VDI
    licensing:
      required: false
      model: open_source
    access:
      sso_required: true
      entitlement_groups:
        - eng_analysis_users
        - phm_analysis_team
        - data_science_team
      export_control: EAR
    workspace:
      mounts_required:
        - repo_node
        - project_exports
        - notebooks
        - shared_datasets
    preflight_checks:
      - check_sso_valid
      - check_entitlement_group
      - check_vdi_session_capacity

# Workspace Mount Types
workspace_mount_types:
  - mount_id: repo_node
    description: "Git repository workspace for current task/project"
    path_template: "/workspace/repos/{project}/{repo}"
    read_write: true
    
  - mount_id: project_exports
    description: "Project-level export directory for deliverables"
    path_template: "/workspace/exports/{project}"
    read_write: true
    
  - mount_id: cad_templates
    description: "CAD template library (standards, part templates)"
    path_template: "/workspace/templates/cad"
    read_write: false
    
  - mount_id: solver_inputs
    description: "Solver input files and configurations"
    path_template: "/workspace/solver/inputs/{project}"
    read_write: true
    
  - mount_id: solver_outputs
    description: "Solver results and output files"
    path_template: "/workspace/solver/outputs/{project}"
    read_write: true
    
  - mount_id: analysis_scripts
    description: "Analysis scripts and calculation templates"
    path_template: "/workspace/scripts/analysis"
    read_write: false
    
  - mount_id: notebooks
    description: "Jupyter notebook working directory"
    path_template: "/workspace/notebooks/{project}"
    read_write: true
    
  - mount_id: shared_datasets
    description: "Shared reference datasets (material properties, test data)"
    path_template: "/workspace/datasets/shared"
    read_write: false

# Preflight Check Definitions
preflight_check_definitions:
  - check_id: check_sso_valid
    description: "Verify user has valid SSO session"
    blocking: true
    
  - check_id: check_entitlement_group
    description: "Verify user is member of required entitlement groups"
    blocking: true
    
  - check_id: check_license_available
    description: "Verify license seat is available for checkout"
    blocking: true
    
  - check_id: check_license_tokens_available
    description: "Verify sufficient license tokens available for job"
    blocking: true
    
  - check_id: check_vdi_session_capacity
    description: "Verify VDI infrastructure has capacity for new session"
    blocking: true
    
  - check_id: check_hpc_queue_capacity
    description: "Verify HPC queue has capacity for job submission"
    blocking: false
    
  - check_id: check_container_capacity
    description: "Verify container orchestration has capacity"
    blocking: true
    
  - check_id: check_storage_quota
    description: "Verify user/project has sufficient storage quota"
    blocking: false
